### PR TITLE
Decoration Widget showing results inline

### PR DESCRIPTION
**Pull request by josdejong**
@dvd101x I made a start with the decorator showing results inline. It's quite cool! It is starting to work, but I still need to tackle the following things:

1. [x] Render the decoration with `block: true`, between the lines instead of between characters. That currently throws the following error: https://discuss.codemirror.net/t/block-decoration-error-uncaught-rangeerror-block-decorations-may-not-be-specified-via-plugins/4102
2. [x] Only re-calculate after a small delay of say 300ms, or only when the user moves to a different line or the editor loses focus or so.
3. [x] Only re-calculate the parts that have been changed 
4. [ ] When results are (temporarily) outdated, render them with an half-faded out color or so.

### CODE REVIEW

**Comment by josdejong** [comment]
I managed to get the decorations rendered as a block after the line where you're typing. Stay tuned...

**Comment by dvd101x** [comment]
I see, it's some fantastic progress!

@josdejong I really like you idea of just updating what is changing. Personally I wouldn't know how to do it but might have some similarities with https://github.com/observablehq/runtime#variables

I don't want to interrupt your flow, I'll chill for a bit and try to keep up later.

**Comment by josdejong** [comment]
This experiment is a lot of fun 😎 . I've now merged the PR, it's in a usable form though it can be improved.

Calculating the results after a delay introduces quite a challenge: the currently rendered decorations are not in sync with the results that you calculate afterwards. I think this can be solved in two ways:

1. The currently implemented way: whilst typing, keep the existing decorations as they are and shift their position up/down when adding/removing characters. This introduces quite some complexity around the edge cases when your cursor is at the same position as a decoration. When evaluating after a delay, replace all decorations with new ones. That is quite straightforward.
2. Alternatively, we could introduce a solution where every expression gets a unique id. When making a change in the document, we need to create a diff that describes which expressions are created/updated/deleted (by expression id). We can directly create/update/delete decorations (by id) accordingly so the decorations are always in sync. After a delay, we can recalculate the expressions and since they have an id, we know exactly which decoration to update with the new decoration. This way, we can also quite easily mark expressions as dirty when we know their result is outdated. This would be the best solution.

The editor now also has a simple mechanism to check whether an expression needs to be re-calculated: when the expression or it's scope (before evaluation) changed. So, basically, when you change an expression doesn't assign a variable, only this expression is recalculated, and when it assigns a variable, all lower down expressions are recalculated. This also room for improvement, for example by filtering the scope by symbols that are actually used in the expression. So, when a variable `width` is changed but the expression doesn't use this variable, it will not recalculate.

**Comment by dvd101x** [comment]
wow! that's super!

- Regarding the results after a delay I like the idea of dividing the expressions that can be identified, I was thinking of the following
  - Put each expression in an array with objects of the form `{source: expression, outputs: null, checked: false}`
    - An expression is a line or series of lines where parse doesn't throw an error to allow for multiple lines expressions
      - If it still throws an error at the end of the document then include it as an expression
  - Find if the expression was already there to see if it's an update, insert, removal.  
  - Do the process of updating the outputs for all the un-checked expressions
  - Adding decorators is done instantly or with an imperceptible delay (just parsing which expression is it and getting it's output if it was already checked)
- Regarding the check whether an expression need to be re-calculated 
  - Maybe instead of updating when the expression changes, should be if the parsing of an expression changes. `math.parse(expression).toString()` so if `2+x` changes to `2  +  x` there is no need to update.

**Comment by josdejong** [comment]
Ah, yes those are some good ideas! handling multiline expressions is a thing indeed, and checking if the parsed expression has changed makes sense.

**Pull request merged**
