### PR TITLE
Updating results of depending expression #11

### PR DESCRIPTION
**Pull request by dvd101x**
This is a fix for #11 

It was referencing a wrong scope.

### CODE REVIEW

**Comment by josdejong** [comment]
Thanks. This does not fully solve the issue though: if you start with this:

```
a=2
b=3
c=a+b
```
and after that add a new variable `d` to the start and use that in the existing expression for `c`, it doesn't work:

```
d=4
a=2
b=3
c=a+b+d # Error: Undefined symbol d
```

I can have a look at it coming Wednesday I expect (will also look at other issues at mathjs then)

**Comment by dvd101x** [comment]
Oh, thanks, I didn't notice that.

I have an idea of what is the cause of that. There might be a flaw in the optimization logic I implemented to reduce the amount of calculations. Let me see if I can fix it in the meanwhile.

**Comment by dvd101x** [comment]
Hi Jos,

While working on #11 I intended to commit to my main branch instead of your main branch.

I think the issue was solved, but please review and advise if something can be donde to fix this.

**Comment by josdejong** [comment]
Thanks, I've tested again and all works like a charm :)

**Pull request closed without merging**
